/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard/orders'
import { Route as DashboardCustomersRouteImport } from './routes/dashboard/customers'
import { Route as DashboardProductsIndexRouteImport } from './routes/dashboard/products/index'
import { Route as DashboardInventoryIndexRouteImport } from './routes/dashboard/inventory/index'
import { Route as DashboardAccountingIndexRouteImport } from './routes/dashboard/accounting/index'
import { Route as DashboardProductsVariantRouteImport } from './routes/dashboard/products/variant'
import { Route as DashboardProductsUomRouteImport } from './routes/dashboard/products/uom'
import { Route as DashboardProductsCategoryRouteImport } from './routes/dashboard/products/category'
import { Route as DashboardProductsBundleRouteImport } from './routes/dashboard/products/bundle'
import { Route as DashboardProductsAllRouteImport } from './routes/dashboard/products/all'
import { Route as DashboardInventoryWarehouseRouteImport } from './routes/dashboard/inventory/warehouse'
import { Route as DashboardInventoryUomConversionRouteImport } from './routes/dashboard/inventory/uom-conversion'
import { Route as DashboardInventoryTransferStockRouteImport } from './routes/dashboard/inventory/transfer-stock'
import { Route as DashboardInventoryProductLocationsRouteImport } from './routes/dashboard/inventory/product-locations'
import { Route as DashboardInventoryLowStockRouteImport } from './routes/dashboard/inventory/low-stock'
import { Route as DashboardInventoryExpiredStockRouteImport } from './routes/dashboard/inventory/expired-stock'
import { Route as DashboardInventoryBatchesRouteImport } from './routes/dashboard/inventory/batches'
import { Route as DashboardAdminMaintenanceRouteImport } from './routes/dashboard/admin/maintenance'
import { Route as DashboardAccountingJournalEntryRouteImport } from './routes/dashboard/accounting/journal-entry'
import { Route as DashboardAccountingIncomeStatementRouteImport } from './routes/dashboard/accounting/income-statement'
import { Route as DashboardAccountingGeneralLedgerRouteImport } from './routes/dashboard/accounting/general-ledger'
import { Route as DashboardAccountingChartOfAccountsRouteImport } from './routes/dashboard/accounting/chart-of-accounts'
import { Route as DashboardAccountingBalanceSheetRouteImport } from './routes/dashboard/accounting/balance-sheet'
import { Route as DashboardAccountingReportsSalesByWarehouseRouteImport } from './routes/dashboard/accounting/reports/sales-by-warehouse'
import { Route as DashboardAccountingReportsSalesByPersonRouteImport } from './routes/dashboard/accounting/reports/sales-by-person'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersRoute = DashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsIndexRoute = DashboardProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInventoryIndexRoute = DashboardInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountingIndexRoute =
  DashboardAccountingIndexRouteImport.update({
    id: '/accounting/',
    path: '/accounting/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProductsVariantRoute =
  DashboardProductsVariantRouteImport.update({
    id: '/products/variant',
    path: '/products/variant',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProductsUomRoute = DashboardProductsUomRouteImport.update({
  id: '/products/uom',
  path: '/products/uom',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsCategoryRoute =
  DashboardProductsCategoryRouteImport.update({
    id: '/products/category',
    path: '/products/category',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProductsBundleRoute = DashboardProductsBundleRouteImport.update({
  id: '/products/bundle',
  path: '/products/bundle',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsAllRoute = DashboardProductsAllRouteImport.update({
  id: '/products/all',
  path: '/products/all',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInventoryWarehouseRoute =
  DashboardInventoryWarehouseRouteImport.update({
    id: '/inventory/warehouse',
    path: '/inventory/warehouse',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardInventoryUomConversionRoute =
  DashboardInventoryUomConversionRouteImport.update({
    id: '/inventory/uom-conversion',
    path: '/inventory/uom-conversion',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardInventoryTransferStockRoute =
  DashboardInventoryTransferStockRouteImport.update({
    id: '/inventory/transfer-stock',
    path: '/inventory/transfer-stock',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardInventoryProductLocationsRoute =
  DashboardInventoryProductLocationsRouteImport.update({
    id: '/inventory/product-locations',
    path: '/inventory/product-locations',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardInventoryLowStockRoute =
  DashboardInventoryLowStockRouteImport.update({
    id: '/inventory/low-stock',
    path: '/inventory/low-stock',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardInventoryExpiredStockRoute =
  DashboardInventoryExpiredStockRouteImport.update({
    id: '/inventory/expired-stock',
    path: '/inventory/expired-stock',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardInventoryBatchesRoute =
  DashboardInventoryBatchesRouteImport.update({
    id: '/inventory/batches',
    path: '/inventory/batches',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminMaintenanceRoute =
  DashboardAdminMaintenanceRouteImport.update({
    id: '/admin/maintenance',
    path: '/admin/maintenance',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAccountingJournalEntryRoute =
  DashboardAccountingJournalEntryRouteImport.update({
    id: '/accounting/journal-entry',
    path: '/accounting/journal-entry',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAccountingIncomeStatementRoute =
  DashboardAccountingIncomeStatementRouteImport.update({
    id: '/accounting/income-statement',
    path: '/accounting/income-statement',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAccountingGeneralLedgerRoute =
  DashboardAccountingGeneralLedgerRouteImport.update({
    id: '/accounting/general-ledger',
    path: '/accounting/general-ledger',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAccountingChartOfAccountsRoute =
  DashboardAccountingChartOfAccountsRouteImport.update({
    id: '/accounting/chart-of-accounts',
    path: '/accounting/chart-of-accounts',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAccountingBalanceSheetRoute =
  DashboardAccountingBalanceSheetRouteImport.update({
    id: '/accounting/balance-sheet',
    path: '/accounting/balance-sheet',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAccountingReportsSalesByWarehouseRoute =
  DashboardAccountingReportsSalesByWarehouseRouteImport.update({
    id: '/accounting/reports/sales-by-warehouse',
    path: '/accounting/reports/sales-by-warehouse',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAccountingReportsSalesByPersonRoute =
  DashboardAccountingReportsSalesByPersonRouteImport.update({
    id: '/accounting/reports/sales-by-person',
    path: '/accounting/reports/sales-by-person',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/accounting/balance-sheet': typeof DashboardAccountingBalanceSheetRoute
  '/dashboard/accounting/chart-of-accounts': typeof DashboardAccountingChartOfAccountsRoute
  '/dashboard/accounting/general-ledger': typeof DashboardAccountingGeneralLedgerRoute
  '/dashboard/accounting/income-statement': typeof DashboardAccountingIncomeStatementRoute
  '/dashboard/accounting/journal-entry': typeof DashboardAccountingJournalEntryRoute
  '/dashboard/admin/maintenance': typeof DashboardAdminMaintenanceRoute
  '/dashboard/inventory/batches': typeof DashboardInventoryBatchesRoute
  '/dashboard/inventory/expired-stock': typeof DashboardInventoryExpiredStockRoute
  '/dashboard/inventory/low-stock': typeof DashboardInventoryLowStockRoute
  '/dashboard/inventory/product-locations': typeof DashboardInventoryProductLocationsRoute
  '/dashboard/inventory/transfer-stock': typeof DashboardInventoryTransferStockRoute
  '/dashboard/inventory/uom-conversion': typeof DashboardInventoryUomConversionRoute
  '/dashboard/inventory/warehouse': typeof DashboardInventoryWarehouseRoute
  '/dashboard/products/all': typeof DashboardProductsAllRoute
  '/dashboard/products/bundle': typeof DashboardProductsBundleRoute
  '/dashboard/products/category': typeof DashboardProductsCategoryRoute
  '/dashboard/products/uom': typeof DashboardProductsUomRoute
  '/dashboard/products/variant': typeof DashboardProductsVariantRoute
  '/dashboard/accounting': typeof DashboardAccountingIndexRoute
  '/dashboard/inventory': typeof DashboardInventoryIndexRoute
  '/dashboard/products': typeof DashboardProductsIndexRoute
  '/dashboard/accounting/reports/sales-by-person': typeof DashboardAccountingReportsSalesByPersonRoute
  '/dashboard/accounting/reports/sales-by-warehouse': typeof DashboardAccountingReportsSalesByWarehouseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/accounting/balance-sheet': typeof DashboardAccountingBalanceSheetRoute
  '/dashboard/accounting/chart-of-accounts': typeof DashboardAccountingChartOfAccountsRoute
  '/dashboard/accounting/general-ledger': typeof DashboardAccountingGeneralLedgerRoute
  '/dashboard/accounting/income-statement': typeof DashboardAccountingIncomeStatementRoute
  '/dashboard/accounting/journal-entry': typeof DashboardAccountingJournalEntryRoute
  '/dashboard/admin/maintenance': typeof DashboardAdminMaintenanceRoute
  '/dashboard/inventory/batches': typeof DashboardInventoryBatchesRoute
  '/dashboard/inventory/expired-stock': typeof DashboardInventoryExpiredStockRoute
  '/dashboard/inventory/low-stock': typeof DashboardInventoryLowStockRoute
  '/dashboard/inventory/product-locations': typeof DashboardInventoryProductLocationsRoute
  '/dashboard/inventory/transfer-stock': typeof DashboardInventoryTransferStockRoute
  '/dashboard/inventory/uom-conversion': typeof DashboardInventoryUomConversionRoute
  '/dashboard/inventory/warehouse': typeof DashboardInventoryWarehouseRoute
  '/dashboard/products/all': typeof DashboardProductsAllRoute
  '/dashboard/products/bundle': typeof DashboardProductsBundleRoute
  '/dashboard/products/category': typeof DashboardProductsCategoryRoute
  '/dashboard/products/uom': typeof DashboardProductsUomRoute
  '/dashboard/products/variant': typeof DashboardProductsVariantRoute
  '/dashboard/accounting': typeof DashboardAccountingIndexRoute
  '/dashboard/inventory': typeof DashboardInventoryIndexRoute
  '/dashboard/products': typeof DashboardProductsIndexRoute
  '/dashboard/accounting/reports/sales-by-person': typeof DashboardAccountingReportsSalesByPersonRoute
  '/dashboard/accounting/reports/sales-by-warehouse': typeof DashboardAccountingReportsSalesByWarehouseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/accounting/balance-sheet': typeof DashboardAccountingBalanceSheetRoute
  '/dashboard/accounting/chart-of-accounts': typeof DashboardAccountingChartOfAccountsRoute
  '/dashboard/accounting/general-ledger': typeof DashboardAccountingGeneralLedgerRoute
  '/dashboard/accounting/income-statement': typeof DashboardAccountingIncomeStatementRoute
  '/dashboard/accounting/journal-entry': typeof DashboardAccountingJournalEntryRoute
  '/dashboard/admin/maintenance': typeof DashboardAdminMaintenanceRoute
  '/dashboard/inventory/batches': typeof DashboardInventoryBatchesRoute
  '/dashboard/inventory/expired-stock': typeof DashboardInventoryExpiredStockRoute
  '/dashboard/inventory/low-stock': typeof DashboardInventoryLowStockRoute
  '/dashboard/inventory/product-locations': typeof DashboardInventoryProductLocationsRoute
  '/dashboard/inventory/transfer-stock': typeof DashboardInventoryTransferStockRoute
  '/dashboard/inventory/uom-conversion': typeof DashboardInventoryUomConversionRoute
  '/dashboard/inventory/warehouse': typeof DashboardInventoryWarehouseRoute
  '/dashboard/products/all': typeof DashboardProductsAllRoute
  '/dashboard/products/bundle': typeof DashboardProductsBundleRoute
  '/dashboard/products/category': typeof DashboardProductsCategoryRoute
  '/dashboard/products/uom': typeof DashboardProductsUomRoute
  '/dashboard/products/variant': typeof DashboardProductsVariantRoute
  '/dashboard/accounting/': typeof DashboardAccountingIndexRoute
  '/dashboard/inventory/': typeof DashboardInventoryIndexRoute
  '/dashboard/products/': typeof DashboardProductsIndexRoute
  '/dashboard/accounting/reports/sales-by-person': typeof DashboardAccountingReportsSalesByPersonRoute
  '/dashboard/accounting/reports/sales-by-warehouse': typeof DashboardAccountingReportsSalesByWarehouseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/customers'
    | '/dashboard/orders'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/accounting/balance-sheet'
    | '/dashboard/accounting/chart-of-accounts'
    | '/dashboard/accounting/general-ledger'
    | '/dashboard/accounting/income-statement'
    | '/dashboard/accounting/journal-entry'
    | '/dashboard/admin/maintenance'
    | '/dashboard/inventory/batches'
    | '/dashboard/inventory/expired-stock'
    | '/dashboard/inventory/low-stock'
    | '/dashboard/inventory/product-locations'
    | '/dashboard/inventory/transfer-stock'
    | '/dashboard/inventory/uom-conversion'
    | '/dashboard/inventory/warehouse'
    | '/dashboard/products/all'
    | '/dashboard/products/bundle'
    | '/dashboard/products/category'
    | '/dashboard/products/uom'
    | '/dashboard/products/variant'
    | '/dashboard/accounting'
    | '/dashboard/inventory'
    | '/dashboard/products'
    | '/dashboard/accounting/reports/sales-by-person'
    | '/dashboard/accounting/reports/sales-by-warehouse'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/customers'
    | '/dashboard/orders'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/accounting/balance-sheet'
    | '/dashboard/accounting/chart-of-accounts'
    | '/dashboard/accounting/general-ledger'
    | '/dashboard/accounting/income-statement'
    | '/dashboard/accounting/journal-entry'
    | '/dashboard/admin/maintenance'
    | '/dashboard/inventory/batches'
    | '/dashboard/inventory/expired-stock'
    | '/dashboard/inventory/low-stock'
    | '/dashboard/inventory/product-locations'
    | '/dashboard/inventory/transfer-stock'
    | '/dashboard/inventory/uom-conversion'
    | '/dashboard/inventory/warehouse'
    | '/dashboard/products/all'
    | '/dashboard/products/bundle'
    | '/dashboard/products/category'
    | '/dashboard/products/uom'
    | '/dashboard/products/variant'
    | '/dashboard/accounting'
    | '/dashboard/inventory'
    | '/dashboard/products'
    | '/dashboard/accounting/reports/sales-by-person'
    | '/dashboard/accounting/reports/sales-by-warehouse'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/customers'
    | '/dashboard/orders'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/accounting/balance-sheet'
    | '/dashboard/accounting/chart-of-accounts'
    | '/dashboard/accounting/general-ledger'
    | '/dashboard/accounting/income-statement'
    | '/dashboard/accounting/journal-entry'
    | '/dashboard/admin/maintenance'
    | '/dashboard/inventory/batches'
    | '/dashboard/inventory/expired-stock'
    | '/dashboard/inventory/low-stock'
    | '/dashboard/inventory/product-locations'
    | '/dashboard/inventory/transfer-stock'
    | '/dashboard/inventory/uom-conversion'
    | '/dashboard/inventory/warehouse'
    | '/dashboard/products/all'
    | '/dashboard/products/bundle'
    | '/dashboard/products/category'
    | '/dashboard/products/uom'
    | '/dashboard/products/variant'
    | '/dashboard/accounting/'
    | '/dashboard/inventory/'
    | '/dashboard/products/'
    | '/dashboard/accounting/reports/sales-by-person'
    | '/dashboard/accounting/reports/sales-by-warehouse'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customers': {
      id: '/dashboard/customers'
      path: '/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof DashboardCustomersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products/': {
      id: '/dashboard/products/'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inventory/': {
      id: '/dashboard/inventory/'
      path: '/inventory'
      fullPath: '/dashboard/inventory'
      preLoaderRoute: typeof DashboardInventoryIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/accounting/': {
      id: '/dashboard/accounting/'
      path: '/accounting'
      fullPath: '/dashboard/accounting'
      preLoaderRoute: typeof DashboardAccountingIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products/variant': {
      id: '/dashboard/products/variant'
      path: '/products/variant'
      fullPath: '/dashboard/products/variant'
      preLoaderRoute: typeof DashboardProductsVariantRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products/uom': {
      id: '/dashboard/products/uom'
      path: '/products/uom'
      fullPath: '/dashboard/products/uom'
      preLoaderRoute: typeof DashboardProductsUomRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products/category': {
      id: '/dashboard/products/category'
      path: '/products/category'
      fullPath: '/dashboard/products/category'
      preLoaderRoute: typeof DashboardProductsCategoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products/bundle': {
      id: '/dashboard/products/bundle'
      path: '/products/bundle'
      fullPath: '/dashboard/products/bundle'
      preLoaderRoute: typeof DashboardProductsBundleRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products/all': {
      id: '/dashboard/products/all'
      path: '/products/all'
      fullPath: '/dashboard/products/all'
      preLoaderRoute: typeof DashboardProductsAllRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inventory/warehouse': {
      id: '/dashboard/inventory/warehouse'
      path: '/inventory/warehouse'
      fullPath: '/dashboard/inventory/warehouse'
      preLoaderRoute: typeof DashboardInventoryWarehouseRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inventory/uom-conversion': {
      id: '/dashboard/inventory/uom-conversion'
      path: '/inventory/uom-conversion'
      fullPath: '/dashboard/inventory/uom-conversion'
      preLoaderRoute: typeof DashboardInventoryUomConversionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inventory/transfer-stock': {
      id: '/dashboard/inventory/transfer-stock'
      path: '/inventory/transfer-stock'
      fullPath: '/dashboard/inventory/transfer-stock'
      preLoaderRoute: typeof DashboardInventoryTransferStockRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inventory/product-locations': {
      id: '/dashboard/inventory/product-locations'
      path: '/inventory/product-locations'
      fullPath: '/dashboard/inventory/product-locations'
      preLoaderRoute: typeof DashboardInventoryProductLocationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inventory/low-stock': {
      id: '/dashboard/inventory/low-stock'
      path: '/inventory/low-stock'
      fullPath: '/dashboard/inventory/low-stock'
      preLoaderRoute: typeof DashboardInventoryLowStockRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inventory/expired-stock': {
      id: '/dashboard/inventory/expired-stock'
      path: '/inventory/expired-stock'
      fullPath: '/dashboard/inventory/expired-stock'
      preLoaderRoute: typeof DashboardInventoryExpiredStockRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inventory/batches': {
      id: '/dashboard/inventory/batches'
      path: '/inventory/batches'
      fullPath: '/dashboard/inventory/batches'
      preLoaderRoute: typeof DashboardInventoryBatchesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/maintenance': {
      id: '/dashboard/admin/maintenance'
      path: '/admin/maintenance'
      fullPath: '/dashboard/admin/maintenance'
      preLoaderRoute: typeof DashboardAdminMaintenanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/accounting/journal-entry': {
      id: '/dashboard/accounting/journal-entry'
      path: '/accounting/journal-entry'
      fullPath: '/dashboard/accounting/journal-entry'
      preLoaderRoute: typeof DashboardAccountingJournalEntryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/accounting/income-statement': {
      id: '/dashboard/accounting/income-statement'
      path: '/accounting/income-statement'
      fullPath: '/dashboard/accounting/income-statement'
      preLoaderRoute: typeof DashboardAccountingIncomeStatementRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/accounting/general-ledger': {
      id: '/dashboard/accounting/general-ledger'
      path: '/accounting/general-ledger'
      fullPath: '/dashboard/accounting/general-ledger'
      preLoaderRoute: typeof DashboardAccountingGeneralLedgerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/accounting/chart-of-accounts': {
      id: '/dashboard/accounting/chart-of-accounts'
      path: '/accounting/chart-of-accounts'
      fullPath: '/dashboard/accounting/chart-of-accounts'
      preLoaderRoute: typeof DashboardAccountingChartOfAccountsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/accounting/balance-sheet': {
      id: '/dashboard/accounting/balance-sheet'
      path: '/accounting/balance-sheet'
      fullPath: '/dashboard/accounting/balance-sheet'
      preLoaderRoute: typeof DashboardAccountingBalanceSheetRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/accounting/reports/sales-by-warehouse': {
      id: '/dashboard/accounting/reports/sales-by-warehouse'
      path: '/accounting/reports/sales-by-warehouse'
      fullPath: '/dashboard/accounting/reports/sales-by-warehouse'
      preLoaderRoute: typeof DashboardAccountingReportsSalesByWarehouseRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/accounting/reports/sales-by-person': {
      id: '/dashboard/accounting/reports/sales-by-person'
      path: '/accounting/reports/sales-by-person'
      fullPath: '/dashboard/accounting/reports/sales-by-person'
      preLoaderRoute: typeof DashboardAccountingReportsSalesByPersonRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardCustomersRoute: typeof DashboardCustomersRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAccountingBalanceSheetRoute: typeof DashboardAccountingBalanceSheetRoute
  DashboardAccountingChartOfAccountsRoute: typeof DashboardAccountingChartOfAccountsRoute
  DashboardAccountingGeneralLedgerRoute: typeof DashboardAccountingGeneralLedgerRoute
  DashboardAccountingIncomeStatementRoute: typeof DashboardAccountingIncomeStatementRoute
  DashboardAccountingJournalEntryRoute: typeof DashboardAccountingJournalEntryRoute
  DashboardAdminMaintenanceRoute: typeof DashboardAdminMaintenanceRoute
  DashboardInventoryBatchesRoute: typeof DashboardInventoryBatchesRoute
  DashboardInventoryExpiredStockRoute: typeof DashboardInventoryExpiredStockRoute
  DashboardInventoryLowStockRoute: typeof DashboardInventoryLowStockRoute
  DashboardInventoryProductLocationsRoute: typeof DashboardInventoryProductLocationsRoute
  DashboardInventoryTransferStockRoute: typeof DashboardInventoryTransferStockRoute
  DashboardInventoryUomConversionRoute: typeof DashboardInventoryUomConversionRoute
  DashboardInventoryWarehouseRoute: typeof DashboardInventoryWarehouseRoute
  DashboardProductsAllRoute: typeof DashboardProductsAllRoute
  DashboardProductsBundleRoute: typeof DashboardProductsBundleRoute
  DashboardProductsCategoryRoute: typeof DashboardProductsCategoryRoute
  DashboardProductsUomRoute: typeof DashboardProductsUomRoute
  DashboardProductsVariantRoute: typeof DashboardProductsVariantRoute
  DashboardAccountingIndexRoute: typeof DashboardAccountingIndexRoute
  DashboardInventoryIndexRoute: typeof DashboardInventoryIndexRoute
  DashboardProductsIndexRoute: typeof DashboardProductsIndexRoute
  DashboardAccountingReportsSalesByPersonRoute: typeof DashboardAccountingReportsSalesByPersonRoute
  DashboardAccountingReportsSalesByWarehouseRoute: typeof DashboardAccountingReportsSalesByWarehouseRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCustomersRoute: DashboardCustomersRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAccountingBalanceSheetRoute: DashboardAccountingBalanceSheetRoute,
  DashboardAccountingChartOfAccountsRoute:
    DashboardAccountingChartOfAccountsRoute,
  DashboardAccountingGeneralLedgerRoute: DashboardAccountingGeneralLedgerRoute,
  DashboardAccountingIncomeStatementRoute:
    DashboardAccountingIncomeStatementRoute,
  DashboardAccountingJournalEntryRoute: DashboardAccountingJournalEntryRoute,
  DashboardAdminMaintenanceRoute: DashboardAdminMaintenanceRoute,
  DashboardInventoryBatchesRoute: DashboardInventoryBatchesRoute,
  DashboardInventoryExpiredStockRoute: DashboardInventoryExpiredStockRoute,
  DashboardInventoryLowStockRoute: DashboardInventoryLowStockRoute,
  DashboardInventoryProductLocationsRoute:
    DashboardInventoryProductLocationsRoute,
  DashboardInventoryTransferStockRoute: DashboardInventoryTransferStockRoute,
  DashboardInventoryUomConversionRoute: DashboardInventoryUomConversionRoute,
  DashboardInventoryWarehouseRoute: DashboardInventoryWarehouseRoute,
  DashboardProductsAllRoute: DashboardProductsAllRoute,
  DashboardProductsBundleRoute: DashboardProductsBundleRoute,
  DashboardProductsCategoryRoute: DashboardProductsCategoryRoute,
  DashboardProductsUomRoute: DashboardProductsUomRoute,
  DashboardProductsVariantRoute: DashboardProductsVariantRoute,
  DashboardAccountingIndexRoute: DashboardAccountingIndexRoute,
  DashboardInventoryIndexRoute: DashboardInventoryIndexRoute,
  DashboardProductsIndexRoute: DashboardProductsIndexRoute,
  DashboardAccountingReportsSalesByPersonRoute:
    DashboardAccountingReportsSalesByPersonRoute,
  DashboardAccountingReportsSalesByWarehouseRoute:
    DashboardAccountingReportsSalesByWarehouseRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
