/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard/orders'
import { Route as DashboardCustomersRouteImport } from './routes/dashboard/customers'
import { Route as DashboardProductsIndexRouteImport } from './routes/dashboard/products/index'
import { Route as DashboardInventoryIndexRouteImport } from './routes/dashboard/inventory/index'
import { Route as DashboardProductsVariantRouteImport } from './routes/dashboard/products/variant'
import { Route as DashboardProductsUomRouteImport } from './routes/dashboard/products/uom'
import { Route as DashboardProductsCategoryRouteImport } from './routes/dashboard/products/category'
import { Route as DashboardProductsBundleRouteImport } from './routes/dashboard/products/bundle'
import { Route as DashboardProductsAllRouteImport } from './routes/dashboard/products/all'
import { Route as DashboardInventoryWarehouseRouteImport } from './routes/dashboard/inventory/warehouse'
import { Route as DashboardInventoryUomConversionRouteImport } from './routes/dashboard/inventory/uom-conversion'
import { Route as DashboardInventoryTransferStockRouteImport } from './routes/dashboard/inventory/transfer-stock'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersRoute = DashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsIndexRoute = DashboardProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInventoryIndexRoute = DashboardInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsVariantRoute =
  DashboardProductsVariantRouteImport.update({
    id: '/products/variant',
    path: '/products/variant',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProductsUomRoute = DashboardProductsUomRouteImport.update({
  id: '/products/uom',
  path: '/products/uom',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsCategoryRoute =
  DashboardProductsCategoryRouteImport.update({
    id: '/products/category',
    path: '/products/category',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProductsBundleRoute = DashboardProductsBundleRouteImport.update({
  id: '/products/bundle',
  path: '/products/bundle',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsAllRoute = DashboardProductsAllRouteImport.update({
  id: '/products/all',
  path: '/products/all',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInventoryWarehouseRoute =
  DashboardInventoryWarehouseRouteImport.update({
    id: '/inventory/warehouse',
    path: '/inventory/warehouse',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardInventoryUomConversionRoute =
  DashboardInventoryUomConversionRouteImport.update({
    id: '/inventory/uom-conversion',
    path: '/inventory/uom-conversion',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardInventoryTransferStockRoute =
  DashboardInventoryTransferStockRouteImport.update({
    id: '/inventory/transfer-stock',
    path: '/inventory/transfer-stock',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/inventory/transfer-stock': typeof DashboardInventoryTransferStockRoute
  '/dashboard/inventory/uom-conversion': typeof DashboardInventoryUomConversionRoute
  '/dashboard/inventory/warehouse': typeof DashboardInventoryWarehouseRoute
  '/dashboard/products/all': typeof DashboardProductsAllRoute
  '/dashboard/products/bundle': typeof DashboardProductsBundleRoute
  '/dashboard/products/category': typeof DashboardProductsCategoryRoute
  '/dashboard/products/uom': typeof DashboardProductsUomRoute
  '/dashboard/products/variant': typeof DashboardProductsVariantRoute
  '/dashboard/inventory': typeof DashboardInventoryIndexRoute
  '/dashboard/products': typeof DashboardProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/inventory/transfer-stock': typeof DashboardInventoryTransferStockRoute
  '/dashboard/inventory/uom-conversion': typeof DashboardInventoryUomConversionRoute
  '/dashboard/inventory/warehouse': typeof DashboardInventoryWarehouseRoute
  '/dashboard/products/all': typeof DashboardProductsAllRoute
  '/dashboard/products/bundle': typeof DashboardProductsBundleRoute
  '/dashboard/products/category': typeof DashboardProductsCategoryRoute
  '/dashboard/products/uom': typeof DashboardProductsUomRoute
  '/dashboard/products/variant': typeof DashboardProductsVariantRoute
  '/dashboard/inventory': typeof DashboardInventoryIndexRoute
  '/dashboard/products': typeof DashboardProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/inventory/transfer-stock': typeof DashboardInventoryTransferStockRoute
  '/dashboard/inventory/uom-conversion': typeof DashboardInventoryUomConversionRoute
  '/dashboard/inventory/warehouse': typeof DashboardInventoryWarehouseRoute
  '/dashboard/products/all': typeof DashboardProductsAllRoute
  '/dashboard/products/bundle': typeof DashboardProductsBundleRoute
  '/dashboard/products/category': typeof DashboardProductsCategoryRoute
  '/dashboard/products/uom': typeof DashboardProductsUomRoute
  '/dashboard/products/variant': typeof DashboardProductsVariantRoute
  '/dashboard/inventory/': typeof DashboardInventoryIndexRoute
  '/dashboard/products/': typeof DashboardProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/customers'
    | '/dashboard/orders'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/inventory/transfer-stock'
    | '/dashboard/inventory/uom-conversion'
    | '/dashboard/inventory/warehouse'
    | '/dashboard/products/all'
    | '/dashboard/products/bundle'
    | '/dashboard/products/category'
    | '/dashboard/products/uom'
    | '/dashboard/products/variant'
    | '/dashboard/inventory'
    | '/dashboard/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/customers'
    | '/dashboard/orders'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/inventory/transfer-stock'
    | '/dashboard/inventory/uom-conversion'
    | '/dashboard/inventory/warehouse'
    | '/dashboard/products/all'
    | '/dashboard/products/bundle'
    | '/dashboard/products/category'
    | '/dashboard/products/uom'
    | '/dashboard/products/variant'
    | '/dashboard/inventory'
    | '/dashboard/products'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/customers'
    | '/dashboard/orders'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/inventory/transfer-stock'
    | '/dashboard/inventory/uom-conversion'
    | '/dashboard/inventory/warehouse'
    | '/dashboard/products/all'
    | '/dashboard/products/bundle'
    | '/dashboard/products/category'
    | '/dashboard/products/uom'
    | '/dashboard/products/variant'
    | '/dashboard/inventory/'
    | '/dashboard/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customers': {
      id: '/dashboard/customers'
      path: '/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof DashboardCustomersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products/': {
      id: '/dashboard/products/'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inventory/': {
      id: '/dashboard/inventory/'
      path: '/inventory'
      fullPath: '/dashboard/inventory'
      preLoaderRoute: typeof DashboardInventoryIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products/variant': {
      id: '/dashboard/products/variant'
      path: '/products/variant'
      fullPath: '/dashboard/products/variant'
      preLoaderRoute: typeof DashboardProductsVariantRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products/uom': {
      id: '/dashboard/products/uom'
      path: '/products/uom'
      fullPath: '/dashboard/products/uom'
      preLoaderRoute: typeof DashboardProductsUomRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products/category': {
      id: '/dashboard/products/category'
      path: '/products/category'
      fullPath: '/dashboard/products/category'
      preLoaderRoute: typeof DashboardProductsCategoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products/bundle': {
      id: '/dashboard/products/bundle'
      path: '/products/bundle'
      fullPath: '/dashboard/products/bundle'
      preLoaderRoute: typeof DashboardProductsBundleRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products/all': {
      id: '/dashboard/products/all'
      path: '/products/all'
      fullPath: '/dashboard/products/all'
      preLoaderRoute: typeof DashboardProductsAllRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inventory/warehouse': {
      id: '/dashboard/inventory/warehouse'
      path: '/inventory/warehouse'
      fullPath: '/dashboard/inventory/warehouse'
      preLoaderRoute: typeof DashboardInventoryWarehouseRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inventory/uom-conversion': {
      id: '/dashboard/inventory/uom-conversion'
      path: '/inventory/uom-conversion'
      fullPath: '/dashboard/inventory/uom-conversion'
      preLoaderRoute: typeof DashboardInventoryUomConversionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inventory/transfer-stock': {
      id: '/dashboard/inventory/transfer-stock'
      path: '/inventory/transfer-stock'
      fullPath: '/dashboard/inventory/transfer-stock'
      preLoaderRoute: typeof DashboardInventoryTransferStockRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardCustomersRoute: typeof DashboardCustomersRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardInventoryTransferStockRoute: typeof DashboardInventoryTransferStockRoute
  DashboardInventoryUomConversionRoute: typeof DashboardInventoryUomConversionRoute
  DashboardInventoryWarehouseRoute: typeof DashboardInventoryWarehouseRoute
  DashboardProductsAllRoute: typeof DashboardProductsAllRoute
  DashboardProductsBundleRoute: typeof DashboardProductsBundleRoute
  DashboardProductsCategoryRoute: typeof DashboardProductsCategoryRoute
  DashboardProductsUomRoute: typeof DashboardProductsUomRoute
  DashboardProductsVariantRoute: typeof DashboardProductsVariantRoute
  DashboardInventoryIndexRoute: typeof DashboardInventoryIndexRoute
  DashboardProductsIndexRoute: typeof DashboardProductsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCustomersRoute: DashboardCustomersRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardInventoryTransferStockRoute: DashboardInventoryTransferStockRoute,
  DashboardInventoryUomConversionRoute: DashboardInventoryUomConversionRoute,
  DashboardInventoryWarehouseRoute: DashboardInventoryWarehouseRoute,
  DashboardProductsAllRoute: DashboardProductsAllRoute,
  DashboardProductsBundleRoute: DashboardProductsBundleRoute,
  DashboardProductsCategoryRoute: DashboardProductsCategoryRoute,
  DashboardProductsUomRoute: DashboardProductsUomRoute,
  DashboardProductsVariantRoute: DashboardProductsVariantRoute,
  DashboardInventoryIndexRoute: DashboardInventoryIndexRoute,
  DashboardProductsIndexRoute: DashboardProductsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
