/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard/orders'
import { Route as DashboardInventoryRouteImport } from './routes/dashboard/inventory'
import { Route as DashboardCustomersRouteImport } from './routes/dashboard/customers'
import { Route as DashboardProductsVariantRouteImport } from './routes/dashboard/products/variant'
import { Route as DashboardProductsCategoryRouteImport } from './routes/dashboard/products/category'
import { Route as DashboardProductsBundleRouteImport } from './routes/dashboard/products/bundle'
import { Route as DashboardProductsAllRouteImport } from './routes/dashboard/products/all'
import { Route as DashboardInventoryWarehouseRouteImport } from './routes/dashboard/inventory/warehouse'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInventoryRoute = DashboardInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersRoute = DashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsVariantRoute =
  DashboardProductsVariantRouteImport.update({
    id: '/products/variant',
    path: '/products/variant',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProductsCategoryRoute =
  DashboardProductsCategoryRouteImport.update({
    id: '/products/category',
    path: '/products/category',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProductsBundleRoute = DashboardProductsBundleRouteImport.update({
  id: '/products/bundle',
  path: '/products/bundle',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsAllRoute = DashboardProductsAllRouteImport.update({
  id: '/products/all',
  path: '/products/all',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInventoryWarehouseRoute =
  DashboardInventoryWarehouseRouteImport.update({
    id: '/warehouse',
    path: '/warehouse',
    getParentRoute: () => DashboardInventoryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/inventory': typeof DashboardInventoryRouteWithChildren
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/inventory/warehouse': typeof DashboardInventoryWarehouseRoute
  '/dashboard/products/all': typeof DashboardProductsAllRoute
  '/dashboard/products/bundle': typeof DashboardProductsBundleRoute
  '/dashboard/products/category': typeof DashboardProductsCategoryRoute
  '/dashboard/products/variant': typeof DashboardProductsVariantRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/inventory': typeof DashboardInventoryRouteWithChildren
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/inventory/warehouse': typeof DashboardInventoryWarehouseRoute
  '/dashboard/products/all': typeof DashboardProductsAllRoute
  '/dashboard/products/bundle': typeof DashboardProductsBundleRoute
  '/dashboard/products/category': typeof DashboardProductsCategoryRoute
  '/dashboard/products/variant': typeof DashboardProductsVariantRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/inventory': typeof DashboardInventoryRouteWithChildren
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/inventory/warehouse': typeof DashboardInventoryWarehouseRoute
  '/dashboard/products/all': typeof DashboardProductsAllRoute
  '/dashboard/products/bundle': typeof DashboardProductsBundleRoute
  '/dashboard/products/category': typeof DashboardProductsCategoryRoute
  '/dashboard/products/variant': typeof DashboardProductsVariantRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/customers'
    | '/dashboard/inventory'
    | '/dashboard/orders'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/inventory/warehouse'
    | '/dashboard/products/all'
    | '/dashboard/products/bundle'
    | '/dashboard/products/category'
    | '/dashboard/products/variant'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/customers'
    | '/dashboard/inventory'
    | '/dashboard/orders'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/inventory/warehouse'
    | '/dashboard/products/all'
    | '/dashboard/products/bundle'
    | '/dashboard/products/category'
    | '/dashboard/products/variant'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/customers'
    | '/dashboard/inventory'
    | '/dashboard/orders'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/inventory/warehouse'
    | '/dashboard/products/all'
    | '/dashboard/products/bundle'
    | '/dashboard/products/category'
    | '/dashboard/products/variant'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inventory': {
      id: '/dashboard/inventory'
      path: '/inventory'
      fullPath: '/dashboard/inventory'
      preLoaderRoute: typeof DashboardInventoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customers': {
      id: '/dashboard/customers'
      path: '/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof DashboardCustomersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products/variant': {
      id: '/dashboard/products/variant'
      path: '/products/variant'
      fullPath: '/dashboard/products/variant'
      preLoaderRoute: typeof DashboardProductsVariantRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products/category': {
      id: '/dashboard/products/category'
      path: '/products/category'
      fullPath: '/dashboard/products/category'
      preLoaderRoute: typeof DashboardProductsCategoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products/bundle': {
      id: '/dashboard/products/bundle'
      path: '/products/bundle'
      fullPath: '/dashboard/products/bundle'
      preLoaderRoute: typeof DashboardProductsBundleRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products/all': {
      id: '/dashboard/products/all'
      path: '/products/all'
      fullPath: '/dashboard/products/all'
      preLoaderRoute: typeof DashboardProductsAllRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inventory/warehouse': {
      id: '/dashboard/inventory/warehouse'
      path: '/warehouse'
      fullPath: '/dashboard/inventory/warehouse'
      preLoaderRoute: typeof DashboardInventoryWarehouseRouteImport
      parentRoute: typeof DashboardInventoryRoute
    }
  }
}

interface DashboardInventoryRouteChildren {
  DashboardInventoryWarehouseRoute: typeof DashboardInventoryWarehouseRoute
}

const DashboardInventoryRouteChildren: DashboardInventoryRouteChildren = {
  DashboardInventoryWarehouseRoute: DashboardInventoryWarehouseRoute,
}

const DashboardInventoryRouteWithChildren =
  DashboardInventoryRoute._addFileChildren(DashboardInventoryRouteChildren)

interface DashboardRouteChildren {
  DashboardCustomersRoute: typeof DashboardCustomersRoute
  DashboardInventoryRoute: typeof DashboardInventoryRouteWithChildren
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProductsAllRoute: typeof DashboardProductsAllRoute
  DashboardProductsBundleRoute: typeof DashboardProductsBundleRoute
  DashboardProductsCategoryRoute: typeof DashboardProductsCategoryRoute
  DashboardProductsVariantRoute: typeof DashboardProductsVariantRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCustomersRoute: DashboardCustomersRoute,
  DashboardInventoryRoute: DashboardInventoryRouteWithChildren,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProductsAllRoute: DashboardProductsAllRoute,
  DashboardProductsBundleRoute: DashboardProductsBundleRoute,
  DashboardProductsCategoryRoute: DashboardProductsCategoryRoute,
  DashboardProductsVariantRoute: DashboardProductsVariantRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
